### ISSUE TITLE
[메인페이지] 메인화면 상품 리스트 만들기

### ISSUE THREAD

**Issue by yejilee0714** [yejilee0714/Blue_Sunset#3]
## TODO
- [x] 상품 타이틀 만들기
- [ ] 상품 리스트 만들기
- [ ] section 하나 구현 후 다른 부분도 동일하게 진행
